project_id = "Surrogate-Network"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[realtime]
enabled = false

[storage]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:9002"
additional_redirect_urls = [
  "http://localhost:9002/auth/confirm",
  "http://127.0.0.1:9002/auth/confirm",
  "http://localhost:9002/auth/recovery",
  "http://127.0.0.1:9002/auth/recovery"
]
jwt_expiry = 3600

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true
max_frequency = "1m"

[auth.email.template.confirmation]
subject = "Confirm your Surrogate Network email"
content_path = "./supabase/templates/confirmation.html"

[edge_runtime]
enabled = false

[analytics]
enabled = false
