// Jest setup file
import '@testing-library/jest-dom'

// Mock Next.js router
jest.mock('next/navigation', () => ({
  useRouter: () => ({
    push: jest.fn(),
    replace: jest.fn(),
    prefetch: jest.fn(),
    back: jest.fn(),
    pathname: '/',
    query: {},
    asPath: '/',
  }),
  usePathname: () => '/',
  useSearchParams: () => new URLSearchParams(),
}))

// Mock Next.js Image component
jest.mock('next/image', () => ({
  __esModule: true,
  default: (props) => {
    const { src, alt, ...rest } = props || {};
    return {
      __html: `<img src="${src}" alt="${alt}" ${Object.keys(rest).map(k => `${k}="${rest[k]}"`).join(' ')} />`,
    };
  },
}))

// Mock Supabase
jest.mock('@/infrastructure/supabase/browser', () => ({
  createClient: jest.fn(() => ({
    from: jest.fn(() => ({
      select: jest.fn(() => ({
        eq: jest.fn(() => ({
          single: jest.fn(() => Promise.resolve({ data: null, error: null })),
        })),
        order: jest.fn(() => ({
          limit: jest.fn(() => Promise.resolve({ data: [], error: null })),
        })),
      })),
    })),
    auth: {
      getUser: jest.fn(() => Promise.resolve({ data: { user: null }, error: null })),
    },
  })),
}))

jest.mock('@/infrastructure/supabase/server', () => ({
  createClient: jest.fn(() => ({
    from: jest.fn(() => ({
      select: jest.fn(() => ({
        eq: jest.fn(() => ({
          single: jest.fn(() => Promise.resolve({ data: null, error: null })),
        })),
        order: jest.fn(() => ({
          limit: jest.fn(() => Promise.resolve({ data: [], error: null })),
        })),
      })),
    })),
    auth: {
      getUser: jest.fn(() => Promise.resolve({ data: { user: null }, error: null })),
    },
  })),
  createServiceClient: jest.fn(() => ({
    from: jest.fn(() => ({
      select: jest.fn(() => ({
        eq: jest.fn(() => ({
          single: jest.fn(() => Promise.resolve({ data: null, error: null })),
        })),
      })),
    })),
  })),
}))

// Mock lucide-react icons
jest.mock('lucide-react', () => ({
  Home: () => null,
  UserPlus: () => null,
  Heart: () => null,
  Search: () => null,
  MessageSquare: () => null,
  Award: () => null,
  User: () => null,
  Settings: () => null,
  LogOut: () => null,
  Bell: () => null,
  Coins: () => null,
  Menu: () => null,
  X: () => null,
  Plus: () => null,
  Shield: () => null,
  Target: () => null,
  Briefcase: () => null,
  FileText: () => null,
  AlertCircle: () => null,
  ChevronDown: () => null,
  ChevronRight: () => null,
  LayoutDashboard: () => null,
  Users: () => null,
  Clock: () => null,
  Trophy: () => null,
  Sparkles: () => null,
  CheckCircle: () => null,
  Loader2: () => null,
  Coffee: () => null,
  MapPin: () => null,
  UserCircle2: () => null,
  Mail: () => null,
  Lock: () => null,
  Link: () => null,
  Link2: () => null,
  Video: () => null,
  Send: () => null,
  TrendingUp: () => null,
  Star: () => null,
  HeartHandshake: () => null,
  MessageCircle: () => null,
  ArrowLeft: () => null,
  MoreVertical: () => null,
  Share2: () => null,
  Flag: () => null,
  Eye: () => null,
  EyeOff: () => null,
  Camera: () => null,
  Image: () => null,
  Film: () => null,
  Music: () => null,
  File: () => null,
  Archive: () => null,
  Trash2: () => null,
  Edit: () => null,
  Save: () => null,
  XCircle: () => null,
  Check: () => null,
  Info: () => null,
  HelpCircle: () => null,
  BookOpen: () => null,
  Compass: () => null,
  Globe: () => null,
  ShieldCheck: () => null,
  UserCheck: () => null,
  UserX: () => null,
  Ban: () => null,
  Gavel: () => null,
  Scale: () => null,
  Hash: () => null,
  AtSign: () => null,
  Phone: () => null,
  Calendar: () => null,
  Clock3: () => null,
  Timer: () => null,
  Repeat: () => null,
  RefreshCw: () => null,
  RotateCcw: () => null,
  SkipBack: () => null,
  SkipForward: () => null,
  Play: () => null,
  Pause: () => null,
  Square: () => null,
  Maximize: () => null,
  Minimize: () => null,
  Monitor: () => null,
  Smartphone: () => null,
  Tablet: () => null,
  Laptop: () => null,
  Desktop: () => null,
  Wifi: () => null,
  WifiOff: () => null,
  Bluetooth: () => null,
  Battery: () => null,
  BatteryCharging: () => null,
  Power: () => null,
  Volume2: () => null,
  VolumeX: () => null,
  Mic: () => null,
  MicOff: () => null,
  CameraOff: () => null,
  Sun: () => null,
  Moon: () => null,
  Cloud: () => null,
  CloudRain: () => null,
  CloudSnow: () => null,
  Zap: () => null,
  Flame: () => null,
  Droplets: () => null,
  Wind: () => null,
  Thermometer: () => null,
  Umbrella: () => null,
  TreePine: () => null,
  Flower: () => null,
  Leaf: () => null,
  Bug: () => null,
  Rocket: () => null,
  Anchor: () => null,
  Plane: () => null,
  Car: () => null,
  Bike: () => null,
  Bus: () => null,
  Train: () => null,
  Ship: () => null,
  MapPin: () => null,
  Navigation: () => null,
  Compass: () => null,
  Globe: () => null,
  Flag: () => null,
  Bookmark: () => null,
  Heart: () => null,
  Star: () => null,
  Smile: () => null,
  Frown: () => null,
  Meh: () => null,
  Angry: () => null,
  Laugh: () => null,
  ThumbsUp: () => null,
  ThumbsDown: () => null,
  Hand: () => null,
  Handshake: () => null,
  Users: () => null,
  User: () => null,
  UserPlus: () => null,
  UserMinus: () => null,
  UserCheck: () => null,
  UserX: () => null,
  UserCircle: () => null,
  Contact: () => null,
  AddressBook: () => null,
  Phone: () => null,
  Mail: () => null,
  MessageSquare: () => null,
  MessageCircle: () => null,
  Send: () => null,
  Inbox: () => null,
  Outbox: () => null,
  Archive: () => null,
  Trash: () => null,
  Trash2: () => null,
  Edit: () => null,
  Edit2: () => null,
  Edit3: () => null,
  Pen: () => null,
  PenTool: () => null,
  Type: () => null,
  Bold: () => null,
  Italic: () => null,
  Underline: () => null,
  Strikethrough: () => null,
  List: () => null,
  ListOrdered: () => null,
  ListChecks: () => null,
  Indent: () => null,
  Outdent: () => null,
  AlignLeft: () => null,
  AlignCenter: () => null,
  AlignRight: () => null,
  AlignJustify: () => null,
  Link: () => null,
  Link2: () => null,
  Unlink: () => null,
  Image: () => null,
  ImagePlus: () => null,
  Video: () => null,
  VideoPlus: () => null,
  Film: () => null,
  Music: () => null,
  Mic: () => null,
  MicOff: () => null,
  Volume2: () => null,
  VolumeX: () => null,
  Play: () => null,
  Pause: () => null,
  Square: () => null,
  SkipBack: () => null,
  SkipForward: () => null,
  Repeat: () => null,
  RefreshCw: () => null,
  RotateCcw: () => null,
  Maximize: () => null,
  Minimize: () => null,
  Monitor: () => null,
  Smartphone: () => null,
  Tablet: () => null,
  Laptop: () => null,
  Desktop: () => null,
  Printer: () => null,
  Scan: () => null,
  Camera: () => null,
  CameraOff: () => null,
  Sun: () => null,
  Moon: () => null,
  Cloud: () => null,
  CloudRain: () => null,
  CloudSnow: () => null,
  Zap: () => null,
  Flame: () => null,
  Droplets: () => null,
  Wind: () => null,
  Thermometer: () => null,
  Umbrella: () => null,
  TreePine: () => null,
  Flower: () => null,
  Leaf: () => null,
  Bug: () => null,
  Rocket: () => null,
  Anchor: () => null,
  Plane: () => null,
  Car: () => null,
  Bike: () => null,
  Bus: () => null,
  Train: () => null,
  Ship: () => null,
  Navigation: () => null,
  Compass: () => null,
  Globe: () => null,
  Flag: () => null,
  Bookmark: () => null,
  Heart: () => null,
  Star: () => null,
  Smile: () => null,
  Frown: () => null,
  Meh: () => null,
  Angry: () => null,
  Laugh: () => null,
  ThumbsUp: () => null,
  ThumbsDown: () => null,
  Hand: () => null,
  Handshake: () => null,
  Users: () => null,
  User: () => null,
  UserPlus: () => null,
  UserMinus: () => null,
  UserCheck: () => null,
  UserX: () => null,
  UserCircle: () => null,
  Contact: () => null,
  AddressBook: () => null,
  Phone: () => null,
  Mail: () => null,
  MessageSquare: () => null,
  MessageCircle: () => null,
  Send: () => null,
  Inbox: () => null,
  Outbox: () => null,
  Archive: () => null,
  Trash: () => null,
  Trash2: () => null,
  Edit: () => null,
  Edit2: () => null,
  Edit3: () => null,
  Pen: () => null,
  PenTool: () => null,
  Type: () => null,
  Bold: () => null,
  Italic: () => null,
  Underline: () => null,
  Strikethrough: () => null,
  List: () => null,
  ListOrdered: () => null,
  ListChecks: () => null,
  Indent: () => null,
  Outdent: () => null,
  AlignLeft: () => null,
  AlignCenter: () => null,
  AlignRight: () => null,
  AlignJustify: () => null,
  Link: () => null,
  Link2: () => null,
  Unlink: () => null,
  Image: () => null,
  ImagePlus: () => null,
  Video: () => null,
  VideoPlus: () => null,
  Film: () => null,
  Music: () => null,
  Mic: () => null,
  MicOff: () => null,
  Volume2: () => null,
  VolumeX: () => null,
  Play: () => null,
  Pause: () => null,
  Square: () => null,
  SkipBack: () => null,
  SkipForward: () => null,
  Repeat: () => null,
  RefreshCw: () => null,
  RotateCcw: () => null,
  Maximize: () => null,
  Minimize: () => null,
  Monitor: () => null,
  Smartphone: () => null,
  Tablet: () => null,
  Laptop: () => null,
  Desktop: () => null,
  Printer: () => null,
  Scan: () => null,
  Camera: () => null,
  CameraOff: () => null,
  Sun: () => null,
  Moon: () => null,
  Cloud: () => null,
  CloudRain: () => null,
  CloudSnow: () => null,
  Zap: () => null,
  Flame: () => null,
  Droplets: () => null,
  Wind: () => null,
  Thermometer: () => null,
  Umbrella: () => null,
  TreePine: () => null,
  Flower: () => null,
  Leaf: () => null,
  Bug: () => null,
  Rocket: () => null,
  Anchor: () => null,
  Plane: () => null,
  Car: () => null,
  Bike: () => null,
  Bus: () => null,
  Train: () => null,
  Ship: () => null,
  MapPin: () => null,
  Navigation: () => null,
  Compass: () => null,
  Globe: () => null,
  Flag: () => null,
  Bookmark: () => null,
  Heart: () => null,
  Star: () => null,
  Smile: () => null,
  Frown: () => null,
  Meh: () => null,
  Angry: () => null,
  Laugh: () => null,
  ThumbsUp: () => null,
  ThumbsDown: () => null,
  Hand: () => null,
  Handshake: () => null,
}));